spring.application.name=SecretChat

spring.datasource.url = jdbc:mysql://localhost:3306/secretchat
spring.datasource.username = root
spring.datasource.password = root

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show_sql = true
