spring.application.name=SecretChat

spring.datasource.url = jdbc:mysql://localhost:3306/secretchat
spring.datasource.username = YOUR_MYSQL_USERNAME
spring.datasource.password = YOUR_MYSQL_USERNAME

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show_sql = true
